[build]
  command = "npm run build"
  publish = ".next" 
  functions = ".next/serverless" 

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PRIVATE_STANDALONE = "true"  # Add this line